# 1. Образ
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

# 2. Копии
replicaCount: 1

# 3. Порты (МЕНЯЕМ НА 8080)
service:
  targetPort: 8080

# 4. Сеть
ingress:
  host: test-nginx.expert-only.ru

# 5. Динамические диски для работы Nginx в ReadOnly режиме
persistence:
  volumes:
    - name: nginx-cache
    - name: nginx-run
    - name: nginx-logs
  mounts:
    - name: nginx-cache
      mountPath: /var/cache/nginx
    - name: nginx-run
      mountPath: /var/run
    - name: nginx-logs
      mountPath: /var/log/nginx

# 6. Лимиты
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# 7. Переменные окружения (Чтобы Nginx знал, что слушать 8080)
env:
  - name: NGINX_PORT
    value: "8080"
