apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: promtail
    targetRevision: 6.16.6
    helm:
      values: |
        config:
          clients:
            - url: http://loki-write.logging.svc.cluster.local:3100/loki/api/v1/push

        # Добавляем дополнительные лейблы, чтобы в Grafana было удобно искать
        extraArgs:
          - -client.external-labels=cluster=my-cluster

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
