apiVersion: v2
name: test=work        # Имя твоего нового приложения
description: Тестовое приложение на базе библиотеки
type: application
version: 1.0.0
appVersion: "1.21.0"
icon: https://githubusercontent.com

dependencies:
  - name: mylib
    version: "0.1.2"    #версию свою , но она должна совпадать с гитхаб репо 
    repository: "oci://ghcr.io/snegzok/charts"
