# 1. Образ (используем безопасную версию nginx)
image:
  repository: busybox
  tag: latest
command: ["sh", "-c", "while true; do echo 'Библиотека работает!'; sleep 5; done"]
ingress:
  enabled: false
service:
  enabled: false

# 2. Копии
replicaCount: 1

# 3. Порты (этот образ по умолчанию слушает 8080)
#service:
#  targetPort: 8080

# 4. Сеть
#ingress:
# host: test-nginx.expert-only.ru

# 5. Динамические диски (минимум, необходимый для этого образа)
persistence:
  # 1. Список томов (ОПИСАНИЕ)
  volumes:
    - name: busibox-tmp
      emptyDir: {}  # <--- ЭТО ДОЛЖНО БЫТЬ ЗДЕСЬ

  # 2. Список точек монтирования (КУДА ПРИКЛЕИТЬ ВНУТРИ)
  mounts:
    - name: busibox-tmp
      mountPath: /tmp/busybox # <--- А ЗДЕСЬ ТОЛЬКО ИМЯ И ПУТЬ

# 6. Лимиты ресурсов
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# 7. Защита (библиотека подставит это в securityContext)
securityContext:
  readOnlyRootFilesystem: true
