apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  APP_TITLE: {{ .Values.config.title | quote }}
  APP_COLOR: {{ .Values.config.color | quote }}
  DEBUG_MODE: {{ .Values.config.debug | quote }}
