---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }} # меняем
  namespace: {{ .Release.Namespace }} # меняем
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }} # меняем 
  template:
    metadata:
      labels:
        app: {{ .Release.Name }} # меняем 
    spec:
      containers:
        - name: {{ .Chart.Name }} # меняем 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" # 
          resources:
            requests:
              memory: "64Mi"   # Минимум 64 Мегабайта
              cpu: "100m"      # Минимум 0.1 ядра (100 милли-ядер)
            limits:
              memory: "128Mi"  # Максимум 128 Мегабайт
              cpu: "500m"      # Максимум 0.5 ядра
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
        #    - secretRef:          # --- ДОБАВЬ ЭТО ---
         #       name: {{ .Release.Name }}-secret
          ports:
            - containerPort: 8080
 # --- ПРОВЕРКИ ---
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
