apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-tg-token    # Имя, которое получит обычный секрет
  namespace: argocd         # Тот же неймсейс, где живет Прометей
spec:
  encryptedData:
    # Твой токен, зашифрованный ключом кластера. 
    # Эту "кашу" из символов можно смело пушить в GitHub.
    token: AgBy9DBy8H...ОченьДлиннаяСтрокаСимволов...==
  template:
    metadata:
      name: alertmanager-tg-token
      namespace: monitoring
    type: Opaque

