---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-tg-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgBsOoIQF82r4qBl+xi0jt2culad9SLCBl4e+LyQRUudZcS3Np//fLIAiQzLv9x99MhyQdkYiaZ2GyKfk11L5lOhmd7lebD/bQSKQ522lC+DrXXjSCDS+J4elxaSfCcFmq5/MuXWUyQZK4lqf0Ukhs5HQ8BF/fCXFMXD/dBwzKzs897TCZrW571opLbRzHP2ZVAafwHwL2Ryc/Nvys8HXCjmeymr2ruGV2SxbbuBA8dMIOMdjkeAzdIFQeorxJaxUA/UXE/yONn97Ef4Ogff2Ps2cqiemZRu+aSDq0wFZxP3wCbauRs0UeelUG1l09K9c6LcViVWmAtlxcHlfq59kaYci8JqS3JAUzx0WDfeMORGI3KvmeYWhWEnQGJdxS2vP+jqsEKIuDXzY/knt7nllRcEIyNbD2QJkJ+w4tHdfpd1cgb9xpoamlThezh5xlbQuNYtuNsCs6aAdyrtko0l2RpX2m2NQ2c6JWWup+joQL0+hnH+JWtPbvP9n3Z0uPpW8HbaUXr32lExeG6dtSlPV3u5laNdTmkMYyo4INHAmMFZxMsD73TG6BSZRBSaYy9lEayq0Zs9GN6Lt1sLzZpeC9W2KVFtw+PdnLaeCfMXJtz7qXLgtozl4jdnYYodiS+Nz7Dp+FOuP5BSmWrzAwbe8MGmAIpj6JI5egveH7Yfp+K8XMzFdCb9xPM5qbMcX9pZkOdKhrRaXOYexUdawdXMAkn6YoXNdWmmcvXQwTqWRQnFxCzSjXsEtDp7cKRmIUjD
  template:
    metadata:
      name: alertmanager-tg-token
      namespace: monitoring
