apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.7.1
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          enabled: false

        alertmanager:
          enabled: true
          alertmanagerSpec:
            replicas: 1
            # Убедитесь, что секрет 'alertmanager-tg-token' создан в namespace: monitoring
            secrets:
              - alertmanager-tg-token
            resources:
              requests:
                memory: 64Mi
                cpu: 50m
              limits:
                memory: 128Mi
                cpu: 100m

          config:
            global:
              resolve_timeout: 5m
            route:
              group_by: ['alertname']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: 'telegram'
              # Отключаем дефолтные маршруты, чтобы не было конфликтов
              routes:
              - receiver: 'null'
                matchers:
                - alertname="Watchdog"

            receivers:
            - name: 'telegram'
              telegram_configs:
              - bot_token_file: '/etc/alertmanager/secrets/alertmanager-tg-token/token'
                chat_id: 7002594285
                send_resolved: true
                parse_mode: 'HTML'
                message: |
                  {{ range .Alerts }}
                  <b>🔥 ALERT: {{ .Labels.alertname }}</b>
                  📌 Приложение: {{ .Labels.app }}
                  📝 Суть: {{ .Annotations.summary }}
                  ⏳ Началось: {{ .StartsAt.Format "15:04:05" }}
                  {{ end }}

            # ДОБАВЛЕНО: Ресивер "null" для исправления ошибки ReconciliationFailed
            - name: 'null'

        prometheus:
          prometheusSpec:
            retention: 6h
            storageSpec:
              emptyDir:
                medium: Memory
            replicas: 1

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
