apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.7.1
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          enabled: false

        alertmanager:
          enabled: true
          
          alertmanagerSpec:
            replicas: 1
            version: v0.27.0
            secrets:
              - alertmanager-tg-token

          config:
            global:
              resolve_timeout: 5m
            route:
              group_by: ['alertname']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: 'telegram'          # ← Должен совпадать с именем receiver
            receivers:
            - name: 'telegram'              # ← Имя receiver'а
              telegram_configs:
              - bot_token_file: '/etc/alertmanager/secrets/alertmanager-tg-token/token'
                chat_id: 7002594285         # ← ТОЛЬКО ЧИСЛО, без кавычек!
                send_resolved: true
                parse_mode: 'HTML'
                message: |
                  {{ range .Alerts }}
                  <b>🔥 ALERT: {{ .Labels.alertname }}</b>
                  📌 Приложение: {{ .Labels.app }}
                  📝 Суть: {{ .Annotations.summary }}
                  ⏳ Началось: {{ .StartsAt.Format "15:04:05" }}
                  {{ end }}

        prometheus:
          prometheusSpec:
            replicas: 1
            version: v2.53.0
            retention: 6h
            storageSpec:
              emptyDir:
                medium: Memory

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
