replicaCount: 1

image:
  repository: python
  tag: 3.9-slim
  pullPolicy: IfNotPresent

service:
  targetPort: 8080

ingress:
  host: telegram.expert-only.ru

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m

nodeSelector: {}
tolerations: []
affinity: {}
