apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki
    targetRevision: 6.6.2
    helm:
      values: |
        loki:
          deploymentMode: SimpleScalable
          auth_enabled: false
          # Эти поля ОБЯЗАТЕЛЬНЫ для версии 6.x
          storage:
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            type: s3
            s3:
              endpoint: loki-minio.logging.svc:9000
              accessKeyId: loki
              secretAccessKey: supersecret
              s3ForcePathStyle: true
              insecure: true

        # Включаем встроенное хранилище для виртуалки
        minio:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
