apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki
    targetRevision: 6.6.2
    helm:
      values: |
        loki:
          deploymentMode: SimpleScalable
          auth_enabled: false
          
          # Обязательная настройка схемы хранения для версии 6.x
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: index_
                  period: 24h

          commonConfig:
            replication_factor: 1

          storage:
            type: s3
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            s3:
              endpoint: loki-prod-minio.logging.svc:9000
              existingSecret: loki-minio-secret
              accessKeyIdKey: access-key
              secretAccessKeyKey: secret-key
              s3ForcePathStyle: true
              insecure: true

        # --- ЭКОНОМНЫЙ MINIO ---
        minio:
          enabled: true
          mode: standalone
          replicas: 1
          existingSecret: loki-minio-secret
          rootUserKey: access-key
          rootPasswordKey: secret-key
          persistence:
            enabled: true
            size: 5Gi
            storageClass: "local-path"
          resources:
            limits:
              memory: 256Mi

        # --- КОМПОНЕНТЫ LOKI (по 1 реплике) ---
        write:
          replicas: 1
          persistence:
            size: 2Gi
          resources:
            limits:
              memory: 512Mi
        
        read:
          replicas: 1
          resources:
            limits:
              memory: 512Mi
        
        backend:
          replicas: 1
          persistence:
            size: 2Gi
          resources:
            limits:
              memory: 512Mi

        gateway:
          enabled: true
          resources:
            limits:
              memory: 64Mi

        # Выключаем кэши для экономии ресурсов
        resultsCache:
          enabled: false
        chunksCache:
          enabled: false
        monitoring:
          selfMonitoring:
            enabled: false
          lokiCanary:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
